semver check

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -17,6 +17,14 @@ jobs:
         uses: actions/setup-node@v6
         with:
           node-version: 24
-      - name: Build
+      - name: Install
         run: |
           npm i
+      - name: Check Semver
+        run: |
+          local currVersion=$(npm pkg get version | tr -d '"')
+          local latestVersion=$(npm view @jim-brighter/lambda-local-runner version)
+          if [[ $currVersion == $latestVersion ]]; then
+            echo "=== VERSION BUMP REQUIRED ==="
+            exit 1
+          fi
